---
- name: Set up xmrig service account
  ansible.builtin.include_tasks: ../../common/tasks/service-account.yml
  vars:
    service_account_name: _xmrig
    service_account_comment: "MiniFleet Maestro — xmrig service account"
