# roles/mining/defaults/main.yml
# xmrig_version and xmrin_sha256sum come from the mining role
# Note that xmrig_version does not include the leading 'v'
xmrig_download_url: "https://github.com/xmrig/xmrig/releases/download/v{{ xmrig_version }}/xmrig-{{ xmrig_version }}-macos-arm64.tar.gz"
xmrig_sha256: "{{ xmrig_sha256sum }}"
xmrig_release_dir: "xmrig-{{ xmrig_version }}"
xmrig_install_dir: "/Users/_xmrig/xmrig"
