# roles/common/tasks/service-account.yml
- name: "Create {{ service_account_name }} service account"
  become: true
  ansible.builtin.user:
    name: "{{ service_account_name }}"
    comment: "{{ service_account_comment }}"
    system: true
    shell: /usr/bin/false
    create_home: true
    home: "/Users/{{ service_account_name }}"
